name: App Release
on: [push]
jobs:
  build-and-deploy-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: node-env-setup
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install
        run: |
          npm install
      - name: build
        run: |
          npm run build --if-present
        env:
          CI: true
          GENERATE_SOURCEMAP: false
          PUBLIC_URL: https://wheel.xinx.me
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
